repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: autopep8-wrapper
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: mixed-line-ending
        args: ['--fix=lf' ]
    -   id: trailing-whitespace
