# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fabian/projects/privat/qmdwiki/mdwiki/gui/mdwiki.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1078, 736)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeToolBar = QtWidgets.QToolBar(self.centralwidget)
        self.treeToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.treeToolBar.setObjectName("treeToolBar")
        self.verticalLayout.addWidget(self.treeToolBar)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(300, 0))
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.toolBarLayout = QtWidgets.QHBoxLayout()
        self.toolBarLayout.setObjectName("toolBarLayout")
        self.toolBar = QtWidgets.QToolBar(self.tab)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        self.toolBarLayout.addWidget(self.toolBar)
        self.uncommitedWarningLabel = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uncommitedWarningLabel.sizePolicy().hasHeightForWidth())
        self.uncommitedWarningLabel.setSizePolicy(sizePolicy)
        self.uncommitedWarningLabel.setObjectName("uncommitedWarningLabel")
        self.toolBarLayout.addWidget(self.uncommitedWarningLabel)
        self.horizontalLayout_7.addLayout(self.toolBarLayout)
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.textEdit = Qsci.QsciScintilla(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setToolTip("")
        self.textEdit.setWhatsThis("")
        self.textEdit.setObjectName("textEdit")
        self.webView = QtWebEngineWidgets.QWebEngineView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.horizontalLayout_7.addWidget(self.splitter)
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 284, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_2 = Qsci.QsciScintilla(self.tab_3)
        self.textEdit_2.setToolTip("")
        self.textEdit_2.setWhatsThis("")
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout.addWidget(self.textEdit_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1078, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRecentWikis = QtWidgets.QMenu(self.menuFile)
        self.menuRecentWikis.setObjectName("menuRecentWikis")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBack = QtWidgets.QAction(MainWindow)
        self.actionBack.setCheckable(True)
        icon = QtGui.QIcon.fromTheme("back")
        self.actionBack.setIcon(icon)
        self.actionBack.setObjectName("actionBack")
        self.actionForward = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("forward")
        self.actionForward.setIcon(icon)
        self.actionForward.setObjectName("actionForward")
        self.actionactionFullscreen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("view-fullscreen")
        self.actionactionFullscreen.setIcon(icon)
        self.actionactionFullscreen.setObjectName("actionactionFullscreen")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setCheckable(True)
        icon = QtGui.QIcon.fromTheme("edit")
        self.actionEdit.setIcon(icon)
        self.actionEdit.setObjectName("actionEdit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("filesave")
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionCommit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("dialog-apply")
        self.actionCommit.setIcon(icon)
        self.actionCommit.setObjectName("actionCommit")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("stock_delete")
        self.actionDelete.setIcon(icon)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSync = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("mail-send-receive")
        self.actionSync.setIcon(icon)
        self.actionSync.setObjectName("actionSync")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("system-shutdown")
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNewWiki = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("folder-new")
        self.actionNewWiki.setIcon(icon)
        self.actionNewWiki.setObjectName("actionNewWiki")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("folder-open")
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.treeToolBar.addAction(self.actionNew)
        self.treeToolBar.addAction(self.actionDelete)
        self.treeToolBar.addAction(self.actionSync)
        self.toolBar.addAction(self.actionBack)
        self.toolBar.addAction(self.actionForward)
        self.toolBar.addAction(self.actionactionFullscreen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionCommit)
        self.menuFile.addAction(self.actionNewWiki)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuRecentWikis.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Filter articles ..."))
        self.uncommitedWarningLabel.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "View"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "History"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "HTML"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuRecentWikis.setTitle(_translate("MainWindow", "Recent Wikis"))
        self.actionBack.setText(_translate("MainWindow", "Back"))
        self.actionForward.setText(_translate("MainWindow", "Forward"))
        self.actionactionFullscreen.setText(_translate("MainWindow", "actionFullscreen"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionCommit.setText(_translate("MainWindow", "Commit"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionSync.setText(_translate("MainWindow", "Sync"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionNewWiki.setText(_translate("MainWindow", "New Wiki ..."))
        self.actionOpen.setText(_translate("MainWindow", "Open ..."))

from PyQt5 import Qsci
from PyQt5 import QtWebEngineWidgets
